name: marus_kit
description: maru&#x27;s Kit
version: 0.0.3
author: Toi Yoshimaru <0maru.dev@gmail.com>
homepage: https://github.com/0maru/marus_kit

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^0.5.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
